name: microservicebus-node
version: '0.1' 
summary: ...
description: |
  microServiceBus.com ® enables businesses to combine the power of Enterprise Application Integration (EAI) with agility and reach of Internet of Things (IoT). https://microservicebus.com/
grade: devel 
confinement: devmode 

apps:
  microservicebus-node:
    command: bin/startsnap

parts:
  node:
    source: https://github.com/qbranch-code/microservicebus-node.git
    source-branch: master
    plugin: nodejs
    node-engine: 7.10.0
